### ISSUE TITLE
make program run even not exist tasks

### ISSUE THREAD

**Issue by Nbdyleto** [Nbdyleto/pyqt5-task-tracker#4]
Traceback (most recent call last):
  File "/home/nbdleto/PCC/daily-task/PyQT5-daily-task/main.py", line 161, in <module>
    window = Window()
  File "/home/nbdleto/PCC/daily-task/PyQT5-daily-task/main.py", line 28, in __init__
    self.main.create_task(5, 5, 6, 'Make Tetris with c#')
  File "/home/nbdleto/PCC/daily-task/PyQT5-daily-task/tasks.py", line 114, in create_task
    task = Task(self.instance_list[topic_id], start_time, end_time, name)
IndexError: list index out of range

**Comment by Nbdyleto** [comment]
### class Main:
    def __init__(self):
        try:
            self.load_tasks()
        except Exception:
            with open('lists.json', 'w') as json_file:
                json.dump('', json_file)
